axis:
  number: 5
calibrate:
  j0: 0
  j1: 145
  j2: -90
  j3: 0
  j4: 0
default_jerk:
  joint:
  - 300
  - 300
  - 300
  - 300
  - 300
  xyz:
  - 50
  - 50
  - 50
  - 300
  - 300
default_speed:
  joint: 1000
  xyz: 100
limit:
  j0:
  - -175.0
  - 175.0
  j1:
  - -175.0
  - 160.0
  j2:
  - -130.0
  - 130.0
motion:
  ct: 0.01
  gpa: 2
  jt: 1
toolhead:
  x: 1.74
unit:
  length: inch
